//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongKham
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public int MaCTHD { get; set; }
        public int MaHoaDon { get; set; }
        public int MaThuoc { get; set; }
        public int SoLuong { get; set; }
        public double ThanhTien { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual Thuoc Thuoc { get; set; }
    }
}
